[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.flash_mode = dio
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    adafruit/Adafruit GFX Library@^1.12.6
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
    https://github.com/LSatan/SmartRC-CC1101-Driver-Lib.git

build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -D CC1101_ENABLED=false